//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coba
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_matakuliah
    {
        public int Id { get; set; }
        public string kode_matkul { get; set; }
        public string nama_matkul { get; set; }
    }
}
